---
version: "3"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/London
    volumes:
      - /path/to/data:/config
      - /path/to/movies:/movies # optional
      - /path/to/downloadclient-downloads:/downloads # optional
    ports:
      - 7878:7878
    restart: unless-stopped


# Services to add:
# prowlarr
# uptime-kuma
# wireguard
# nginxproxymanager
# homer
# jellyfin
# sonarr