---
version: "3"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/London
    volumes:
      - /srv/data/radarr:/config
      - /srv/media/movies:/movies
      - /srv/staging/movies:/movies
    ports:
      - 7878:7878
    restart: unless-stopped
  readarr:
    image: lscr.io/linuxserver/readarr:latest
    container_name: readarr
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/London
    volumes:
      - /srv/data/readarr:/config
      - /srv/media/books:/books
      - /srv/staging/books:/books
    ports:
      - 8787:8787
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/London
    volumes:
      - /srv/data/sonarr:/config
      - /srv/media/tv:/tv
      - /srv/staging/tv:/tv
    ports:
      - 8989:8989
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/London
    volumes:
      - /srv/data/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - /srv/data/homer/assets:/www/assets
    ports:
      - 8246:8246
    user: 1000:1000
    environment:
      - INIT_ASSETS=1
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /srv/data/jellyfin:/config
      - /srv/media/tv:/tv
      - /srv/media/movies:/movies
      - /srv/media/music:/music
      - /srv/media/books:/books
    ports:
      - 8096:8096
      - 7359:7359/udp
      - 1900:1900/udp
    restart: unless-stopped
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - /srv/data/uptime-kuma:/app/data
    ports:
      - 3001:3001
    restart: always
  nginxproxymanager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    environment:
      # Uncomment this if IPv6 is not enabled on your host
      DISABLE_IPV6: 'true'
    volumes:
      - /srv/data/nginxreverseproxy:/data
      - /srv/data/nginxreverseproxy:/etc/letsencrypt
  watchtower:
    image: containrrr/watchtower
    volumes:
      -  /var/run/docker.sock:/var/run/docker.sock
  actual-server:
    image: actualbudget/actual-server:latest
    ports:
      - '5006:5006'
    volumes:
      - /srv/data/actual:/data
    restart: unless-stopped
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    environment:
      - TZ=Europe/London
    volumes:
      - /var/cache/ntfy:/var/cache/ntfy
      - /etc/ntfy:/etc/ntfy
    ports:
      - 80:80 # Change port in /etc/ntfy/server.yml
    healthcheck: # optional: remember to adapt the host:port to your environment
        test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s
    restart: unless-stopped

    
# Services to add:

# qBittorrent
# grafana
# prometheus